### ISSUE TITLE
Issue with kong_postgres.yml on GCE

### ISSUE THREAD

**Issue by FGRibreau** [Mashape/kong-dist-kubernetes#13]
Hello !

The default configuration did not worked, I started:

```
kubectl create -n kong -f postgres.yml
kubectl create -n kong -f kong_postgres.yml
```

and looking at `/usr/local/kong/logs/` I saw kong was not able to convert `KONG_PG_HOST` to the IP address. To make it work (for testing) I had to edit kong_postgres.yml and put the real IP of the postgres host.

Note: once connected through bash to the kong RC pod, I was able to resolve the `postgres.kong` host so the real issue is not clear to me.

**Comment by shashiranjan84** [comment]
@FGRibreau are you running Kong in `default` namespace?

**Comment by shashiranjan84** [comment]
@FGRibreau closing this issue. Please reopen, with more details, if you are still facing the issue.
