### ISSUE TITLE
Multiple replicas don't pick up admin updates. 

### ISSUE THREAD

**Issue by mitcheaton1** [Mashape/kong-dist-kubernetes#18]
Maybe not an issue but more of a question. If I have 2 kong replicas, and I make an an update to the admin service to add a route to kong, It seems like only the replica that received the request via the admin service is updated. I need to restart the other pod for it to pick up the changes in postgres. Is this expected? Not a huge deal as routes don't change often, but I was wondering if there was away to notify the other replicas once one has been updated. They are all using an external postgres store.  Seems like Kong is storing or doing something in memory on the pod that received teh admin API request.

**Comment by shashiranjan84** [comment]
@mitcheaton1 as long as kong provisioned as [cluster](https://getkong.org/docs/0.10.x/clustering/), any change made to one node should be propagated to another node. Make sure Kong is able to talk to each other over  port  7946(UDP, TCP both). Try running reachability test on one of the Kong nodes.

**Comment by shashiranjan84** [comment]
@mitcheaton1 closing the issue, feel free to reopen if issue persists with more details.
