### ISSUE TITLE
Backup/restore cluster

### ISSUE THREAD

**Issue by aubm** [Mashape/kong-dist-kubernetes#2]
Hey!

Thank you for the repo, it helped me to get started fairly quickly.
I don't have that much experience with Kubernetes, so maybe my question has at least one obvious answer that I can't see for now.

What strategy would you use when using Kubernetes on Google Container Engine, for backup Cassandra data?

Cheers.

**Comment by shashiranjan84** [comment]
You can mount a persistent disk,  hove a look at following links for more insight

http://kubernetes.io/docs/user-guide/volumes/
https://github.com/kubernetes/kubernetes/tree/master/examples/storage/cassandra

**Comment by jimmiebtlr** [comment]
@aubm 

To note on that, the example from the primary repo is currently not applicable for GKE.  StatefulSets/PetSets aren't available in current stable gke, believe they're still listed as alpha.  

The docs on persistant volumes, also not sure if that's particularly applicable, as from my understanding they actually cause the same volume to be mounted across all the pods (probably don't want that for cassandra).  My understanding is pretty limited at the moment, so this part may well be wrong.

If you find a way to make it work with the persistent volumes, I'd be interested, currently not sure of an easy way to manage persistent cassandra in kuberenetes.
