### ISSUE TITLE
Question about comment in cassandra.yaml file

### ISSUE THREAD

**Issue by gsf-sellis** [Mashape/kong-dist-kubernetes#23]
Hi, can someone please explain what this comment means in the cassandra.yaml file?

`# do not use these in production until ssd GCEPersistentDisk or other ssd pd`

Thanks,
Scott

**Comment by shashiranjan84** [comment]
Its is a recommendation for running Cassandra in production environment. You have option to store Cassandra data on standard HDD or SSD. SSD provide fast IOPS and recommended for production environment. 

Some helpful links:

https://kubernetes.io/docs/concepts/storage/persistent-volumes/#gce
https://cloud.google.com/compute/docs/disks/
http://blog.kubernetes.io/2016/10/dynamic-provisioning-and-storage-in-kubernetes.html
https://kubernetes.io/docs/tutorials/stateful-application/cassandra/
