### ISSUE TITLE
Crash on kong >v0.9.1 

### ISSUE THREAD

**Issue by ismailbaskin** [Mashape/kong-dist-kubernetes#3]
It works when image: kong:0.9.0, but kong:0.9.1 image cannot resolve _kong-database_ on runtime. I've checked with nslookup and telnet and these are resolve properly _kong-database_ . 

> 2016/11/23 08:39:20 [error] 107#0: [lua] cluster.lua:41: [postgres error] kong-database could not be resolved (2: Server failure), context: ngx.timer
> 2016/11/23 08:39:23 [error] 107#0: [lua] cluster.lua:41: [postgres error] kong-database could not be resolved (2: Server failure), context: ngx.timer
> 2016/11/23 08:39:26 [error] 107#0: [lua] postgres_db.lua:41: failed to cleanup TTLs: kong-database could not be resolved (2: Server failure), context: ngx.timer
> 2016/11/23 08:39:26 [error] 107#0: [lua] cluster.lua:82: [postgres error] kong-database could not be resolved (2: Server failure), context: ngx.timer
> 2016/11/23 08:39:26 [error] 108#0: [lua] postgres_db.lua:41: failed to cleanup TTLs: kong-database could not be resolved (2: Server failure), context: ngx.timer
> 2016/11/23 08:39:26 [error] 107#0: [lua] cluster.lua:41: [postgres error] kong-database could not be resolved (2: Server failure), context: ngx.timer

**Comment by ismailbaskin** [comment]
Maybe its related https://github.com/Mashape/kong/issues/1104 i tried many things but still doesn't work

**Comment by DonMartin76** [comment]
I can just say I have the exact same problems.

**Comment by DonMartin76** [comment]
Workaround if you have provisioned the service for the database before starting Kong: Use the "old school" discovery mechanisms over environment variables to fill the `KONG_PG_HOST` (or the corresponding Cassandra variable) before starting Kong. This will require you to create a custom image `FROM kong:0.9.5` with a small script.

See [Haufe-Lexware/wicked.kong](https://github.com/Haufe-Lexware/wicked.kong) (branch `next`, `startup.sh`) for an example.

It assumes that there is a service which is called `kong-database`, and that the host is stored in `KONG_DATABASE_SERVICE_HOST` (which will automatically be the case).

**Comment by DonMartin76** [comment]
You can also use the same technique if you want to proxy services which reside inside the Kubernetes Cluster. Kong won't be able to resolve those either unfortunately, so there you will also need to supply the IP address of the service instead of the DNS name ("service:1234") of the service.

**Comment by ismailbaskin** [comment]
Thank you @DonMartin76 . I think [this](https://github.com/Mashape/kong/issues/1601#issuecomment-245474404) solution is more appropriate.
