### ISSUE TITLE
Integration as Ingress Controller

### ISSUE THREAD

**Issue by pabloguerrero** [Mashape/kong-dist-kubernetes#4]
Are there any plans to integrate Kong as an Ingress Controller (like those [here](https://github.com/kubernetes/contrib/tree/master/ingress/controllers))?

**Comment by shashiranjan84** [comment]
Maybe as a new plugin, I would advise creating a ticket here https://github.com/Mashape/kong/issues

**Comment by inluxc** [comment]
Theres is one.
https://github.com/kolihub/kong-ingress
